package ru.demax.simplelook.components;

import com.webobjects.appserver.WOContext;

import er.extensions.components.ERXStatelessComponent;

// Generated by the WOLips Templateengine Plug-in at Jan 16, 2008 6:04:34 PM
public class DMButton extends ERXStatelessComponent {
    public DMButton(WOContext context) {
        super(context);
    }
}