package ru.demax.simplelook.components;

import com.webobjects.appserver.WOContext;
import com.webobjects.directtoweb.D2WContext;

import er.extensions.components.ERXNonSynchronizingComponent;

// Generated by the WOLips Templateengine Plug-in at Dec 26, 2007 6:23:34 PM
public class DMInnerPageWrapper extends ERXNonSynchronizingComponent {
    public DMInnerPageWrapper(WOContext context) {
        super(context);
    }
    
    public D2WContext d2wContext() {
    	return (D2WContext) parent().valueForKey("d2wContext");
    }

    public String wrapperDivCssClass() {
    	StringBuffer result =  new StringBuffer(d2wContext().pageName());
    	result.append(" ");
    	result.append(d2wContext().dynamicPage()); 

    	String wrapperClass = (String) d2wContext().valueForKey("wrapperCssClass");
    	if (wrapperClass != null) {
    		result.append(" ");
    		result.append(wrapperClass);
		}
    	
    	return result.toString();
    }
}